INDIGO_WELCOME_MESSAGE: "A computational thinking, coding, and data literacy program for Grades 5-12"
INDIGO_PRIMARY_COLOR: "#3b85ff" # cool blue

# Footer links are dictionaries with a "title" and "url"
# Example:
# INDIGO_FOOTER_NAV_LINKS:
#   - title: "About"
#     url: "http://mywebsite/about"
#   - title: "Donate"
#     url: "http://mywebsite/donations"
INDIGO_FOOTER_NAV_LINKS:
  - title: "About Us"
    url: "https://callysto.ca/callysto/"
  - title: "Cybera"
    url: "https://www.cybera.ca/"
  - title: "Pacific Institute of Mathematical Sciences"
    url: "https://www.pims.math.ca/"
  - title: "The Government of Canada"
    url: "https://www.ic.gc.ca/eic/site/121.nsf/eng/home"

INDIGO_FOOTER_LEGAL_LINKS:
  - title: "Terms of Service"
    url: "https://callysto.ca/wp-content/uploads/2020/01/CallystoLearningSystem-TermsofService-January2020.pdf"
  - title: "Privacy Policy"
    url: "https://callysto.ca/wp-content/uploads/2020/01/CallystoLearningSystem-PrivacyNotice-January2020.pdf"
